Backend
anitaschiller/capstone-project pull request #11
Opened 2021-04-06 14:43 UTC by anitaschiller

Branch for the backend

I built the server part of my app and connected it with the frontend. Image upload/cropping and the edit form on the details page can be ignored since they are part of other PRs which are currently still open.

Thank you! :-)

2021-04-06 17:00 UTC, ThomasKirst requested changes
Nice work 👏 

Only a few remarks. The server looks very good overall! 👍

2021-04-06 17:00 UTC, ThomasKirst commented on client/src/App.js
> +  }, []);
This `useEffect()` could do both fetch calls within one effect function.

2021-04-06 17:00 UTC, ThomasKirst commented on client/src/App.js
> +      .catch((error) => console.error(error.message));
👍

2021-04-06 17:00 UTC, ThomasKirst commented on client/src/App.js
>      const upToDateMembers = members.filter(
```suggestion
  function updateMember(memberToUpdate) {
    const upToDateMembers = members.filter(
```

2021-04-06 17:00 UTC, ThomasKirst commented on client/src/App.js
> +    const remainingMembers = members.filter(
Could this function get the id of the record to be deleted as a parameter? Otherwise it relies on a variable outside of the context of the function.

2021-04-06 17:00 UTC, ThomasKirst commented on client/src/App.js
> +      (member) => member.group === groupToDelete.name
Does the `groupToDelete` not have an `_id` property that can be used later on?

2021-04-06 17:00 UTC, ThomasKirst commented on client/src/pages/Home.js
>              <Delete onClick={() => deleteGroup(group)}>&times;</Delete>
Maybe simply pass the `_id` of the group here?

2021-04-06 17:00 UTC, ThomasKirst commented on server/src/controller/groups.controller.js
> +  const newGroup = new Group({
A guard checking for the group´s name would be advisable here. `if (!request.body.name) …`

2021-04-06 17:00 UTC, ThomasKirst commented on server/src/controller/groups.controller.js
> +  Group.findOneAndDelete({ _id: idToDelete }).catch((error) =>
Is there no response ( `then(() => response.json(…)` ) for the success case?

2021-04-06 17:00 UTC, ThomasKirst commented on server/src/controller/members.controller.js
> +}
👍

2021-04-06 17:00 UTC, ThomasKirst commented on server/src/controller/members.controller.js
> +  Member.findOneAndDelete({ _id: idToDelete }).catch((error) =>
Response in case of success would be nice.

2021-04-06 17:00 UTC, ThomasKirst commented on server/src/routes/members.routes.js
> +router.delete('/:memberId', deleteMember);
```suggestion
router.get('/members', getMembers);
router.post('/members', postMember);
router.put('/members/:memberId', updateMember);
router.delete('/members/:memberId', deleteMember);
```

2021-04-06 17:02 UTC, ThomasKirst commented
Please make sure to solve the conflicts in these files:

```
client/src/App.js
client/src/components/Form.js
client/src/pages/Home.js
```

Maybe it's best to pull the latest main branch into your feature branch.

2021-04-07 10:18 UTC, anitaschiller commented on client/src/App.js
> +      (member) => member.group === groupToDelete.name
It does, but my member.group is just a string without the id. But I will think about changing that :-).

2021-04-07 10:35 UTC, anitaschiller commented on server/src/controller/groups.controller.js
> +  Group.findOneAndDelete({ _id: idToDelete }).catch((error) =>
Now there is :-)

2021-04-07 10:42 UTC, merged