Delete functions
anitaschiller/capstone-project pull request #5
Opened 2021-03-24 12:09 UTC by anitaschiller

Branch for user stories: Delete member/delete member Entry-card

I added a few functions that make deleting a single member on the "home" page as well as a member entry on the "details" page possible. New is also the DeletionModal component that makes sure that a member can only be deleted upon confirmation.

Next step: Create remember tags

Thank you!! :-)

2021-03-24 15:27 UTC, basti-n commented on client/src/App.js
> +  console.log('remainingMebers', remainingMembers);
No console.logs on main.

2021-03-24 15:37 UTC, basti-n commented on client/src/pages/Details.js
> +      setNewMember(updatedMember);
Both these functions seem to always be called together. Maybe useful to encapsulate the calling in a separate function. This new function would then make sure both functions are called.

2021-03-24 15:52 UTC, miriamhaenle requested changes
Hi Anita, 
nice job again! I added a few comments. 
Please also take a look  again at your files. There are a lot of console.logs still present. It is not considered good practice to merge console.logs into main (only use it while developing). I did highlight a few but please check again and remove them. 

I also noticed quite a few comments, especially in your Details.js. Please also take a look again if these comments are really needed in order to understand your code. Ideally comments are use scarcely and only where the code itself can not convey its intention fully.

On a more general note you can take a look again at your colors. You have defined some global variables, sometimes use HTML color names and sometimes hex values. Try to stick with one approach if possible :) Something you could change later on in the project.

👍

2021-03-24 15:52 UTC, miriamhaenle commented on client/src/App.js
> +    console.log('deleteMember');
```suggestion

```

2021-03-24 15:52 UTC, miriamhaenle commented on client/src/App.js
> +    console.log('confirmDeletion');
```suggestion
```

2021-03-24 15:52 UTC, miriamhaenle commented on client/src/pages/Details.js
> +  console.log('newMember', newMember);
```suggestion
```

2021-03-24 15:52 UTC, miriamhaenle commented on client/src/pages/Details.js
> +    members.find((newMember) => newMember.id === member.id)
Maybe you can encapsulate this into its own function with a descriptive name and thus won't need the comment in line 16
`const findCurrentMember = (newMember) => members.find(member => member.Id === newMember.id)`

2021-03-25 08:37 UTC, anitaschiller commented
> Hi Anita,
> nice job again! I added a few comments.
> Please also take a look again at your files. There are a lot of console.logs still present. It is not considered good practice to merge console.logs into main (only use it while developing). I did highlight a few but please check again and remove them.
> 
> I also noticed quite a few comments, especially in your Details.js. Please also take a look again if these comments are really needed in order to understand your code. Ideally comments are use scarcely and only where the code itself can not convey its intention fully.
> 
> On a more general note you can take a look again at your colors. You have defined some global variables, sometimes use HTML color names and sometimes hex values. Try to stick with one approach if possible :) Something you could change later on in the project.
> 
> 👍

Ouh yes, I totally forgot to clean up this time, but will do before I merge! Thank you for looking through and all your comments! :-)

2021-03-27 10:28 UTC, merged